<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>NeuralFoil.NET</AssemblyName>
	  <AssemblyTitle>NeuralFoil.NET</AssemblyTitle>
    <Description>Port of NeuralFoil core inference to .NET.</Description>
	  <PackageId>NeuralFoil.NET</PackageId>
	  <RepositoryUrl>https://github.com/StuYarrow/NeuralFoil.NET</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RootNamespace>NeuralFoil</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <Import Project="..\GlobalAssemblyInfo.csproj" />

  <ItemGroup>
    <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <None Include="..\..\NeuralFoil\neuralfoil\nn_weights_and_biases\*.npz">
      <Link>nn_weights_and_biases\%(RecursiveDir)/%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles/any/netstandard2.1</PackagePath>
      <PackageCopyToOutput>true</PackageCopyToOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

</Project>
