name: Release

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'true'
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'
    - name: Get major version
      id: get_major_version
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: './src/GlobalAssemblyInfo.csproj'
        xpath: '//MajorVersion'
    - name: Get minor version
      id: get_minor_version
      uses: mavrosxristoforos/get-xml-info@2.0
      with:
        xml-file: './src/GlobalAssemblyInfo.csproj'
        xpath: '//MinorVersion'
    - name: Get build number
      id: get_build_number
      env:
        major: ${{ steps.get_major_version.outputs.info }}
        minor: ${{ steps.get_minor_version.outputs.info }}
      run: echo "build_number=`bash ./get-build-number.sh -M ${major} -m ${minor}`" >> $GITHUB_OUTPUT
    - name: Restore
      run: dotnet restore ./NeuralFoil.NET.sln
    - name: Build
      run: >
        dotnet build
        -c Release
        --no-restore
        -p:BuildNumber=${{ steps.get_build_number.outputs.build_number }}
        ./NeuralFoil.NET.sln
    - name: Test
      run: >
        dotnet test
        -c Release
        --no-restore
        --no-build
        ./NeuralFoil.NET.sln
    - name: Pack
      run: >
        dotnet pack
        -c Release
        --no-restore
        --no-build
        -p:BuildNumber=${{ steps.get_build_number.outputs.build_number }}
        ./src/NeuralFoil.NET/NeuralFoil.NET.csproj
    - name: Create release
      uses: softprops/action-gh-release@v3
      env:
        RELEASE: v${{ steps.get_major_version.outputs.info }}.${{ steps.get_minor_version.outputs.info }}.${{ steps.get_build_number.outputs.build_number }}
      with:
        target_commitish: release
        tag_name: ${{ env.RELEASE }}
        name: ${{ env.RELEASE }}
        files: ./src/artifacts/package/release/*.nupkg
